[tool.poetry]
name = "django-tailwind"
version = "1.1.1"
description = "Tailwind CSS Framework for Django projects"
authors = ["Tim Kamanin <tim@timonweb.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/timonweb/django-tailwind"
keywords = ["django", "tailwind", "css"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
    "Environment :: Web Environment",
    "Framework :: Django"
]
packages = [
    { include = "tailwind" }
]

[tool.poetry.dependencies]
python = "^3.7"
django = ">=2.2"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
pytest-django = "^3.8.0"
tox = "^3.14.3"
pre-commit = "^2.6.0"
isort = "^5.6.4"
flake8 = "^3.8.4"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
